### ISSUE TITLE
Measure app's times under stress

### ISSUE THREAD

**Issue by namesty** [polywrap/fund-public-goods#163]
Response times can be as small as 1 minute but if I do many in a row it starts to take more. I think me might be getting throttled by OpenAI

A few things we can do easily to reduce time are:

- Storing embeddings in pinecone, now that we are more confident in our vector search strategy. This can shave a lot of time because it would save us from fetching all projects from supabase and then creating embeddings for the relevant ones. (like 10 less seconds I think)

- Caching impact and funding needed scores. This would shortcut the evaluation by a ton but would require a bit more work as report generation and scoring would need to be separated into 'relevancy' and 'impact & funding needed'

**Comment by dOrgJelli** [comment]
Both of these have been completed
